### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "jason@example.com",
  "password": "password"
}

### Get All Loads
GET http://localhost:3000/loads
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYTAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAxIiwiaWF0IjoxNzc3OTUwOTkxLCJleHAiOjE3Nzc5NTQ1OTF9.9pFwfhZo-NmlO8WdjXJAuUYZZyo3OV2e53LcLDL_oVM

###

### Get Single Load
GET http://localhost:3000/loads/a1d06215-1642-4931-9c0a-3f9925dc7a66
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYTAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAxIiwiaWF0IjoxNzc3OTUwOTkxLCJleHAiOjE3Nzc5NTQ1OTF9.9pFwfhZo-NmlO8WdjXJAuUYZZyo3OV2e53LcLDL_oVM

###

### Get All Brokers
GET http://localhost:3000/brokers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYTAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAxIiwiaWF0IjoxNzc2NTYzNTI1LCJleHAiOjE3NzY1NjcxMjV9.xyutv-WJePpyv5uPxjLSF_lW23idQrWv9YSkWxOkLjQ

### GET ALL AGENTS
GET http://localhost:3000/agents
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYTAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAxIiwiaWF0IjoxNzc2NTYzNTI1LCJleHAiOjE3NzY1NjcxMjV9.xyutv-WJePpyv5uPxjLSF_lW23idQrWv9YSkWxOkLjQ

### GET ALL MARKETS
GET http://localhost:3000/markets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYTAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAxIiwiaWF0IjoxNzc2NTYzNTI1LCJleHAiOjE3NzY1NjcxMjV9.xyutv-WJePpyv5uPxjLSF_lW23idQrWv9YSkWxOkLjQ

### Create Agent
POST http://localhost:3000/agents
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYTAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAxIiwiaWF0IjoxNzc3MjQzNjc1LCJleHAiOjE3NzcyNDcyNzV9.EqCCaDCTRo-bF6Ep3yGFNLrix5ucGz7yxrxBwSCKJnM
Content-Type: application/json

{
  "broker_id": "d0000000-0000-0000-0000-000000000001",
  "first_name": "Test",
  "last_name": "Agent",
  "phone": null,
  "email": "test@test.com",
  "preferred_contact": "email",
  "rating": null,
  "notes": null
}